namespace Craiel.UnityGameData.Editor.Enums
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public static class GameDataEditorEnumValues
    {
        // -------------------------------------------------------------------
        // Auto Generated by AudioEnumValues.tt DO NOT MODIFY DIRECTLY!
        // -------------------------------------------------------------------
        public static readonly IList<GameDataEditorConfigKeys> GameDataEditorConfigKeysValues = Enum.GetValues(typeof(GameDataEditorConfigKeys)).Cast<GameDataEditorConfigKeys>().ToList();

        public static readonly IList<GameDataEditorViewMode> GameDataEditorViewModeValues = Enum.GetValues(typeof(GameDataEditorViewMode)).Cast<GameDataEditorViewMode>().ToList();

    }
}
