namespace Craiel.UnityGameData.Editor.Enums
{
    using System.Collections.Generic;
    using System.Linq;
    using UnityEssentials.Runtime;

    public static class GameDataEditorEnumValues
    {
        // -------------------------------------------------------------------
        // Auto Generated by AudioEnumValues.tt DO NOT MODIFY DIRECTLY!
        // -------------------------------------------------------------------
        public static readonly IList<GameDataEditorConfigKeys> GameDataEditorConfigKeysValues = EnumCache<GameDataEditorConfigKeys>.Values.ToList();

        public static readonly IList<GameDataEditorViewMode> GameDataEditorViewModeValues = EnumCache<GameDataEditorViewMode>.Values.ToList();

    }
}
